version: '3'
services:
  postgres:
    image: 'postgres:9.6-alpine'
    restart: always
    container_name: postgres-dojo
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - '5433:5432'