spring:

---
spring:
  profiles: local-test
  datasource:
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: ci-test
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: 'jdbc:postgresql://localhost:5433/test_db'
    username: local
    password: local
